added clothing recommendations depending on the weather
AngelikaC98/groupProject2 pull request #13
Opened 2024-10-08 11:32 UTC by HeiddisBirta

added clothing recommendations depending on the weather with multiple options, have not yet added photos

2024-10-08 12:09 UTC, utlandingur commented on __tests__/clothingRecs.test.js
"use strict" is something from next.js and isn't required here

You are using commonJS importing (i.e. require statements) but we should use ES6. e.g.  import {clothingRecs} from "../utils"

This awaiter function is hard to read and overly complicated.
We just need to follow basic principles. e.g. 
> Arrange: Set up the test. This could involve creating objects, setting up mock data, or setting initial conditions.
> Act: Perform the action that you're testing. This is usually a single function call.
> Assert: Check that the results are what you expect. This could involve checking return values, checking the state of an object, or checking that certain methods were called.

so often something like
const input = ...
con expectedOutput = ...
expect(functionToTest(input)).isEqualTo(expectedOutput) or something like that

2024-10-08 12:11 UTC, utlandingur commented on __tests__/clothingRecs.test.ts
It will be easier to read and understand following an approach like this

const input = ...
con expectedOutput = ...
expect(functionToTest(input)).isEqualTo(expectedOutput) or something like that

2024-10-08 12:13 UTC, utlandingur commented on index.html
we dont need to put a script in yet.
And we would probably use a different approach to use it

2024-10-08 12:16 UTC, utlandingur commented on utils.ts
might be easier to read if we deconstruct first.
const {temp,rain,wind} = weather. 

Then you can avoid writing weather 12 times.

What haoppens if no conditions are met? I think we should have a default case

2024-10-08 12:16 UTC, utlandingur requested changes
Some comments to work through have been added.
Please remove the JS files

2024-10-08 17:08 UTC, HeiddisBirta commented on __tests__/clothingRecs.test.ts
I think this approach works better for me, I can change it tomorrow if it's important to you that we use the approach you mentioned above :)

2024-10-09 12:02 UTC, utlandingur commented on fetchData/getWeatherData.js
I think we should delete this js file as well.
We will likely run tsc on the whole project and have the output files in a single distribution folder. Again, which we can do next week

2024-10-09 12:04 UTC, utlandingur commented on frontend/src/utils.ts
So I've just remembered that we're getting the forecast for the whole day, and the commute involves the journey there and back.

This handles a point in time but what should we be recommending for the whole day?
I still also think we should have a default case other than undefined.

2024-10-09 12:05 UTC, utlandingur commented on utils.js
We can remove this utils.js file for now.

2024-10-09 12:07 UTC, utlandingur requested changes
Just a couple of really small things I suggest removing.

Overall I think its good - but I just realised that we're returning a recommendation based on a snapshot in time, but the commute also involves a journey back. So it would be good if we could account for that - OR if we have a suggestion for the way there and another for the way back.

What do you think?

2024-10-09 17:32 UTC, HeiddisBirta commented
Added clothing options for morning (the first one available in array) and afternoon (time right now), this was very complicated for me and I feel like I'm not able to wrap my head around all of the things in the code so this was the only thing I could do with a lot of help. I´m open to discussing it tomorrow, I´ve spent way to long on only this thing

2024-10-10 10:04 UTC, AngelikaC98 approved these changes
everything it´s correct written

2024-10-10 10:06 UTC, utlandingur approved these changes
Happy with changes

2024-10-10 10:07 UTC, merged